### PR TITLE
Fix deprecation warning for Ruby 2.7 in base.rb.

### LINKED ISSUE #659: Ruby 2.7 deprecation warning
### Expected behavior

I'd expect no deprecation warnings to be caused by sprockets on Ruby 2.7.

### Actual behavior

When running my test suite with Ruby 2.7 I see this deprecation warning:

```
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sprockets-4.0.0/lib/sprockets/base.rb:119: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sprockets-4.0.0/lib/sprockets/base.rb:78: warning: The called method `find_asset' is defined here
```

I tried a quick fix that changes [`base.rb`](https://github.com/rails/sprockets/blob/c4b191e70d89e9d70f19ade5faf0692054a3bd1b/lib/sprockets/base.rb#L119) to use a doublesplat, which fixes the deprecation but then causes a new one in sprockets-rails because it calls the `[]` method :P

```ruby
def [](*args, **options)
  find_asset(*args, **options)
end
```

### System configuration

- Sprockets version: 4.0.0
- Ruby version: 2.7.0

### Example App (Reproduction)

My app VideoGameList is where I'm seeing this, specifically if you run the test suite with Ruby 2.7 on my `test-ruby-2-7` branch: https://github.com/connorshea/VideoGameList/commit/ce84ad20ace4b7bbdf98b6fc5644967ed2641eb3

It'd probably be easier to just run the Sprockets test suite on Ruby 2.7, though. You'll probably see the same deprecation warning that way.

### PR DESCRIPTION
**Pull request by connorshea**
Resolves #659. This causes a new deprecation warning in sprockets-rails, but I'm opening a PR in sprockets-rails to fix that next.

### CODE REVIEW

**Comment by connorshea** [comment]
https://github.com/rails/sprockets-rails/pull/454 actually may be the only PR that needs to be merged here. The deprecation warning is fixed by the change in sprockets-rails regardless of whether this change is present.

That said, if the deprecation warning weren't fixed in sprockets, I wouldn't have known that there was a problem in sprockets-rails. So I think this might be worth fixing to make it easier to determine the true source of deprecation warnings in other gems.

File: lib/sprockets/base.rb [hunk 1]
```diff
@@ -115,8 +115,8 @@ def find_all_linked_assets(*args)
     #
     #     environment['application.js']
     #
-    def [](*args)
-      find_asset(*args)
+    def [](*args, **options)
```
Comment (rafaelfranca) [inline lib/sprockets/base.rb]: The spockets-rails method call should not raise any warning since it is passing a hash as second argument, not keyword arguments.

Comment (rafaelfranca) [reply lib/sprockets/base.rb]: Ah, I see. It is because `find_asset` is doing the split.

**Comment by yahonda** [comment]
@rafaelfranca Would you consider to release the next version of sprockets including this fix? Since Rails 6.0.3 has been released to address Ruby 2.7 keyword arguments deprecation warnings. 
sprockets 4.0.0 and sprockets-rails 3.2.1 still show these warnings.

**Comment by rafaelfranca** [comment]
Yes, it is on my list I'm doing sometime next week
