### PR TITLE
Fix unregister processor behaviour for class names

### LINKED ISSUE #266: environment.unregister_processor doesn't unregister processor
I have a simple directive processor that looks for javascript in some non-standard directories. I followed [this comment](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/directive_processor.rb#L155-L176) in my implementation.

    class JsDirectiveProcessor < DirectiveProcessor
      def process_npm_directive(path)
        uri, deps = @environment.resolve!(path, accept: @content_type, pipeline: :self, load_paths: Dir["#{Rails.root}/**/node_modules"])
        @dependencies.merge(deps)
        @required << uri
      end
    end

Then I unregister the original and register my processor.

    Rails.application.config.assets.configure do |env|
      env.unregister_processor('application/javascript', Sprockets::DirectiveProcessor)
      env.register_processor('application/javascript', JsDirectiveProcessor)
    end

The files are included, but out of order. Dependencies included via `require` are included before the `npm` dependencies. Dropping a debugger into `configure` shows that `env.processors` contains multiple classes despite unregister.

    (byebug) env.processors
    {"application/javascript"=>[JsDirectiveProcessor, #<Sprockets::DirectiveProcessor:0x007fdb83737a38 @header_pattern=/\A(?:(?m:\s*)(?:(?:\/\/.*\n?)+|(?:\/\*(?m:.*?)\*\/)|(?:\#.*\n?)+|(?:\#\#\#(?m:.*?)\#\#\#)))+/>]}

### PR DESCRIPTION
**Pull request by Strech**
Closes #266

This example will unregister all registered processors of given class
(instances and classes):

```ruby
Rails.application.config.assets.configure do |env|
  env.unregister_processor('application/javascript', Sprockets::DirectiveProcessor)
end
```

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@Strech Thanks! Can you update the commit message to point to issue #266 instead of #226 😸 ?

File: test/test_environment.rb [hunk 1]
```diff
@@ -746,6 +746,19 @@ def foo; end
     @env.unregister_preprocessor('application/javascript', processor)
     assert_equal "// =require \"notfound\"\n;\n", @env["missing_require.js"].to_s
   end
+
+  test "disabling processors by class name" do
```
Comment (prathamesh-sonpatki) [inline test/test_environment.rb]: Can you update the test name to `disabling processors by class name also disables processors which are instances of that class` to make it more clear?

File: test/test_environment.rb [hunk 2]
```diff
@@ -746,6 +746,19 @@ def foo; end
...
+    class SpaceAndWhitespaceCompressor < WhitespaceCompressor; end
```
Comment (prathamesh-sonpatki) [inline test/test_environment.rb]: Can you define this class inline? 

Like `SpaceAndWhitespaceCompressor = Class.new(WhitespaceCompressor)`

**Comment by prathamesh-sonpatki** [comment]
This change looks good. 

For more reference -- https://github.com/rails/sprockets/issues/266#issuecomment-239464157

**Comment by Strech** [comment]
@prathamesh-sonpatki thanks for your review, will push fixes

**Comment by Strech** [comment]
@prathamesh-sonpatki Test description, issue number, and code style are fixed

**Comment by Strech** [comment]
@schneems If you have a time, can you 👀 on this PR?

**Comment by schneems** [comment]
Thanks! This looks good. @Strech you're killing it 🚀
